### ISSUE TITLE
У Вас есть код, меняющий исходные леммы на разные грамматические формы?

### ISSUE THREAD

**Issue by richiebful** [LinguisticAndInformationSystems/mphdict#1]
Я вижу, что есть морфологические данные и программа, показывающая эти данные. Вы можете показать мне, как вы разработали эти базы данных? Я с моими коллегами разработаю подобный грамматический словарь в цель компьютерного анализа русской поэзии. А я хотел проверить наш словарь, и узнать какие методы вы использовали. И, бесусловно, будем ссылаться на ваш словарь.

**Comment by uSofTrod** [comment]
Для БД граматичного словника російської мови первинним джерелом лінгвістичної інформації в першу чергу слугував «Грамматический словарь русского языка» А. А. Залізняка (https://ru.wikipedia.org/wiki/Грамматический_словарь_русского_языка_А._А._Зализняка), для української мови - це наявні орфографічні словники. Далі - це робота кваліфікованих прикладних лінгвістів.
